import * as Lucide from 'lucide-react-native';
import { text } from '../tokens/colors';
import { iconSize } from '../tokens/spacing';

const MAP: Record<string, keyof typeof Lucide> = {
  home: 'Home',
  'chat-bubble-outline': 'MessageCircle',
  bolt: 'Zap',
  psychology: 'BrainCircuit',
  'monitor-heart': 'Activity',
  'edit-note': 'StickyNote',
  'developer-board': 'Cpu',
  settings: 'Settings',
  memory: 'Cpu',
  storage: 'HardDrive',
  'battery-full': 'BatteryFull',
  'wb-sunny': 'Sun',
  'arrow-upward': 'ArrowUp',
  mic: 'Mic',
  stop: 'Square',
  campaign: 'Megaphone',
  'arrow-forward-ios': 'ChevronRight',
  lock: 'Lock',
  bedtime: 'Moon',
  'restart-alt': 'RefreshCw',
  'power-settings-new': 'Power',
  'volume-up': 'Volume2',
  'music-note': 'Music',
  'skip-previous': 'SkipBack',
  'play-arrow': 'Play',
  pause: 'Pause',
  'skip-next': 'SkipForward',
  code: 'Code',
  edit: 'Pencil',
  terminal: 'Terminal',
  folder: 'Folder',
  'sports-esports': 'Gamepad2',
  'content-copy': 'Copy',
  'content-paste': 'ClipboardPaste',
  newspaper: 'Newspaper',
  search: 'Search',
  'settings-ethernet': 'EthernetPort',
  'error-outline': 'AlertCircle',
  'check-circle': 'CheckCircle',
  'info-outline': 'Info',
  'hourglass-empty': 'Hourglass',
  schedule: 'Clock',
  'hard-drive': 'HardDrive',
  description: 'FileText',
  'chevron-right': 'ChevronRight',
  'arrow-back': 'ArrowLeft',
  add: 'Plus',
  'add-circle': 'PlusCircle',
  close: 'X',
  check: 'Check',
  'wifi-find': 'Wifi',
  save: 'Save',
  dns: 'Globe',
  key: 'KeyRound',
  menu: 'Menu',
  fingerprint: 'Fingerprint',
  language: 'Globe',
  chat: 'MessageSquare',
  'grid-view': 'Grid2x2',
  'volume-off': 'VolumeX',
  monitor: 'Monitor',
  favorite: 'Heart',
  globe: 'Globe',
  pin: 'Pin',
  refresh: 'RefreshCw',
  trash: 'Trash2',
  network: 'Network',
  'activity': 'Activity',
  'cpu': 'Cpu',
  'thermometer': 'Thermometer',
  'clock': 'Clock',
  'calendar': 'Calendar',
  'user': 'User',
  'shield': 'Shield',
  'alert': 'AlertTriangle',
  'bell': 'Bell',
  'bookmark': 'Bookmark',
  'briefcase': 'Briefcase',
  'camera': 'Camera',
  'cloud': 'Cloud',
  'compass': 'Compass',
  'database': 'Database',
  'download': 'Download',
  'external-link': 'ExternalLink',
  'eye': 'Eye',
  'file': 'File',
  'filter': 'Filter',
  'flag': 'Flag',
  'flash': 'Zap',
  'gift': 'Gift',
  'hash': 'Hash',
  'headphones': 'Headphones',
  'heart': 'Heart',
  'image': 'Image',
  'inbox': 'Inbox',
  'info': 'Info',
  'layers': 'Layers',
  'link': 'Link',
  'list': 'List',
  'loader': 'Loader',
  'location': 'MapPin',
  'log-in': 'LogIn',
  'log-out': 'LogOut',
  'mail': 'Mail',
  'map': 'Map',
  'maximize': 'Maximize2',
  'minimize': 'Minimize2',
  'minus': 'Minus',
  'more-horizontal': 'MoreHorizontal',
  'more-vertical': 'MoreVertical',
  'move': 'Move',
  'package': 'Package',
  'paperclip': 'Paperclip',
  'phone': 'Phone',
  'pie-chart': 'PieChart',
  'play': 'Play',
  'plus': 'Plus',
  'printer': 'Printer',
  'radio': 'Radio',
  'rotate': 'RotateCw',
  'rss': 'Rss',
  'scissors': 'Scissors',
  'send': 'Send',
  'server': 'Server',
  'share': 'Share2',
  'shopping-cart': 'ShoppingCart',
  'sliders': 'Sliders',
  'smartphone': 'Smartphone',
  'speaker': 'Speaker',
  'star': 'Star',
  'sun': 'Sun',
  'tablet': 'Tablet',
  'tag': 'Tag',
  'target': 'Target',
  'thumbs-down': 'ThumbsDown',
  'thumbs-up': 'ThumbsUp',
  'toggle': 'ToggleLeft',
  'tool': 'Wrench',
  'trending-down': 'TrendingDown',
  'trending-up': 'TrendingUp',
  'truck': 'Truck',
  'tv': 'Tv',
  'umbrella': 'Umbrella',
  'unlock': 'Unlock',
  'upload': 'Upload',
  'video': 'Video',
  'voicemail': 'Voicemail',
  'watch': 'Watch',
  'wifi': 'Wifi',
  'wind': 'Wind',
  'zap': 'Zap',
  'zoom-in': 'ZoomIn',
  'zoom-out': 'ZoomOut',
  'expand-less': 'ChevronUp',
  'expand-more': 'ChevronDown',
  'picture-as-pdf': 'FileText',
  'folder-zip': 'Archive',
  'video-file': 'Video',
  'presentation': 'Monitor',
  'application': 'Monitor',
  'more-vert': 'MoreVertical',
  'swap-horiz': 'ArrowLeftRight',
  'screenshot': 'Monitor',
  'focus-mode': 'Eye',
  'clipboard-history': 'ClipboardList',
  'system-update': 'RefreshCw',
  'volume-down': 'Volume1',
  'repeat': 'Repeat',
  'shuffle': 'Shuffle',
  'queue-music': 'ListMusic',
};

type Props = {
  name: string;
  size?: number;
  color?: string;
};

export default function Icon({ name, size = iconSize.list, color = text.primary }: Props) {
  const iconName = MAP[name];
  if (!iconName) {
    const Fallback = Lucide.Circle;
    return <Fallback size={size} color={color} />;
  }
  const LucideIcon = Lucide[iconName] as any;
  if (!LucideIcon) {
    const Fallback = Lucide.Circle;
    return <Fallback size={size} color={color} />;
  }
  return <LucideIcon size={size} color={color} />;
}
