import type { StateConfig, OrbState } from './OrbTypes';

export const STATE_CONFIGS: Record<OrbState, StateConfig> = {
  disconnected: {
    coreColor1: '#3A1A1A',
    coreColor2: '#6B1F1F',
    pulseDuration: 2500,
    pulseSpread: 0.3,
    glowColor: 'rgba(69,26,26,0.16)',
    glowIntensity: 0.1,
    haloVisible: false,
    haloRotationMs: 0,
    ringsVisible: 1,
    ringsOpacity: 0.08,
    ringsColor: '#FF5A61',
    ringScale: 1,
    ringPulseOpacity: { from: 0.04, to: 0.08 },
    ringsRotateMs: 0,
    particlesActive: false,
    particleType: 'none',
    particleCount: 0,
    particleColor: '#FF5A61',
    particleSpeed: 1,
    floatAmplitude: 1,
    floatDuration: 6000,
    breathingAmplitude: 0.01,
    speechDriven: false,
  },

  connecting: {
    coreColor1: '#2A1A0A',
    coreColor2: '#7F4F00',
    pulseDuration: 1200,
    pulseSpread: 0.5,
    glowColor: 'rgba(255,184,77,0.16)',
    glowIntensity: 0.2,
    haloVisible: false,
    haloRotationMs: 0,
    ringsVisible: 1,
    ringsOpacity: 0.12,
    ringsColor: '#FFB84D',
    ringScale: 1,
    ringPulseOpacity: { from: 0.05, to: 0.12 },
    ringsRotateMs: 0,
    particlesActive: false,
    particleType: 'none',
    particleCount: 0,
    particleColor: '#FFB84D',
    particleSpeed: 1,
    floatAmplitude: 1,
    floatDuration: 6000,
    breathingAmplitude: 0.02,
    speechDriven: false,
  },

  idle: {
    coreColor1: '#00E5F2',
    coreColor2: '#628CFF',
    pulseDuration: 4200,
    pulseSpread: 0.02,
    glowColor: 'rgba(0,229,242,0.20)',
    glowIntensity: 0.2,
    haloVisible: false,
    haloRotationMs: 0,
    ringsVisible: 1,
    ringsOpacity: 0.1,
    ringsColor: '#00E5F2',
    ringScale: 1,
    ringPulseOpacity: { from: 0.06, to: 0.1 },
    ringsRotateMs: 0,
    particlesActive: true,
    particleType: 'drift',
    particleCount: 8,
    particleColor: '#52F7FF',
    particleSpeed: 1,
    floatAmplitude: 4,
    floatDuration: 6000,
    breathingAmplitude: 0.02,
    speechDriven: false,
  },

  listening: {
    coreColor1: '#35E69A',
    coreColor2: '#00E5F2',
    pulseDuration: 900,
    pulseSpread: 0.08,
    glowColor: 'rgba(53,230,154,0.28)',
    glowIntensity: 0.32,
    haloVisible: false,
    haloRotationMs: 0,
    ringsVisible: 2,
    ringsOpacity: 0.45,
    ringsColor: '#35E69A',
    ringScale: 1.12,
    ringPulseOpacity: { from: 0.2, to: 0.45 },
    ringsRotateMs: 0,
    particlesActive: false,
    particleType: 'none',
    particleCount: 0,
    particleColor: '#35E69A',
    particleSpeed: 1,
    floatAmplitude: 2,
    floatDuration: 5000,
    breathingAmplitude: 0.08,
    speechDriven: false,
  },

  thinking: {
    coreColor1: '#FFB84D',
    coreColor2: '#B88CFF',
    pulseDuration: 1800,
    pulseSpread: 0.04,
    glowColor: 'rgba(184,140,255,0.28)',
    glowIntensity: 0.24,
    haloVisible: true,
    haloRotationMs: 21000,
    ringsVisible: 1,
    ringsOpacity: 0.25,
    ringsColor: '#B88CFF',
    ringScale: 1,
    ringPulseOpacity: { from: 0.1, to: 0.25 },
    ringsRotateMs: 21000,
    particlesActive: true,
    particleType: 'orbit',
    particleCount: 4,
    particleColor: '#B88CFF',
    particleSpeed: 1.6,
    floatAmplitude: 2,
    floatDuration: 7000,
    breathingAmplitude: 0.04,
    speechDriven: false,
  },

  searching: {
    coreColor1: '#628CFF',
    coreColor2: '#00E5F2',
    pulseDuration: 1200,
    pulseSpread: 0.05,
    glowColor: 'rgba(98,140,255,0.24)',
    glowIntensity: 0.24,
    haloVisible: false,
    haloRotationMs: 0,
    ringsVisible: 1,
    ringsOpacity: 0.3,
    ringsColor: '#628CFF',
    ringScale: 1,
    ringPulseOpacity: { from: 0.12, to: 0.3 },
    ringsRotateMs: 15000,
    particlesActive: true,
    particleType: 'converge',
    particleCount: 3,
    particleColor: '#00E5F2',
    particleSpeed: 1.3,
    floatAmplitude: 2,
    floatDuration: 6000,
    breathingAmplitude: 0.03,
    speechDriven: false,
  },

  memory_retrieval: {
    coreColor1: '#B88CFF',
    coreColor2: '#628CFF',
    pulseDuration: 900,
    pulseSpread: 0.06,
    glowColor: 'rgba(184,140,255,0.24)',
    glowIntensity: 0.24,
    haloVisible: true,
    haloRotationMs: 30000,
    ringsVisible: 1,
    ringsOpacity: 0.2,
    ringsColor: '#B88CFF',
    ringScale: 1,
    ringPulseOpacity: { from: 0.08, to: 0.2 },
    ringsRotateMs: 0,
    particlesActive: true,
    particleType: 'orbit',
    particleCount: 3,
    particleColor: '#B88CFF',
    particleSpeed: 0.9,
    floatAmplitude: 1,
    floatDuration: 7000,
    breathingAmplitude: 0.03,
    speechDriven: false,
  },

  executing: {
    coreColor1: '#B88CFF',
    coreColor2: '#00E5F2',
    pulseDuration: 700,
    pulseSpread: 0.08,
    glowColor: 'rgba(184,140,255,0.28)',
    glowIntensity: 0.28,
    haloVisible: true,
    haloRotationMs: 0,
    ringsVisible: 2,
    ringsOpacity: 0.3,
    ringsColor: '#00E5F2',
    ringScale: 1,
    ringPulseOpacity: { from: 0.12, to: 0.3 },
    ringsRotateMs: 0,
    particlesActive: true,
    particleType: 'orbit',
    particleCount: 3,
    particleColor: '#00E5F2',
    particleSpeed: 1.2,
    floatAmplitude: 1,
    floatDuration: 6000,
    breathingAmplitude: 0.04,
    speechDriven: false,
  },

  speaking: {
    coreColor1: '#00F2FF',
    coreColor2: '#B88CFF',
    pulseDuration: 0,
    pulseSpread: 0.1,
    glowColor: 'rgba(0,242,255,0.5)',
    glowIntensity: 0.5,
    haloVisible: false,
    haloRotationMs: 0,
    ringsVisible: 2,
    ringsOpacity: 0.3,
    ringsColor: '#00F2FF',
    ringScale: 1.2,
    ringPulseOpacity: { from: 0.15, to: 0.35 },
    ringsRotateMs: 0,
    particlesActive: true,
    particleType: 'orbit',
    particleCount: 4,
    particleColor: '#00F2FF',
    particleSpeed: 1.1,
    floatAmplitude: 2,
    floatDuration: 5000,
    breathingAmplitude: 0.05,
    speechDriven: true,
  },

  success: {
    coreColor1: '#35E69A',
    coreColor2: '#00E5F2',
    pulseDuration: 800,
    pulseSpread: 0.09,
    glowColor: 'rgba(53,230,154,0.24)',
    glowIntensity: 0.24,
    haloVisible: false,
    haloRotationMs: 0,
    ringsVisible: 2,
    ringsOpacity: 0.2,
    ringsColor: '#35E69A',
    ringScale: 1,
    ringPulseOpacity: { from: 0.08, to: 0.2 },
    ringsRotateMs: 0,
    particlesActive: true,
    particleType: 'drift',
    particleCount: 3,
    particleColor: '#35E69A',
    particleSpeed: 1,
    floatAmplitude: 1,
    floatDuration: 7000,
    breathingAmplitude: 0.03,
    speechDriven: false,
  },

  warning: {
    coreColor1: '#FFB84D',
    coreColor2: '#FFD080',
    pulseDuration: 900,
    pulseSpread: 0.05,
    glowColor: 'rgba(255,184,77,0.2)',
    glowIntensity: 0.2,
    haloVisible: false,
    haloRotationMs: 0,
    ringsVisible: 1,
    ringsOpacity: 0.15,
    ringsColor: '#FFB84D',
    ringScale: 1,
    ringPulseOpacity: { from: 0.06, to: 0.15 },
    ringsRotateMs: 0,
    particlesActive: false,
    particleType: 'none',
    particleCount: 0,
    particleColor: '#FFB84D',
    particleSpeed: 1,
    floatAmplitude: 1.5,
    floatDuration: 6000,
    breathingAmplitude: 0.02,
    speechDriven: false,
  },

  error: {
    coreColor1: '#7F2A2A',
    coreColor2: '#FF5A61',
    pulseDuration: 320,
    pulseSpread: 0.08,
    glowColor: 'rgba(255,90,97,0.16)',
    glowIntensity: 0.16,
    haloVisible: false,
    haloRotationMs: 0,
    ringsVisible: 1,
    ringsOpacity: 0.35,
    ringsColor: '#FF5A61',
    ringScale: 1,
    ringPulseOpacity: { from: 0.12, to: 0.35 },
    ringsRotateMs: 0,
    particlesActive: false,
    particleType: 'none',
    particleCount: 0,
    particleColor: '#FF5A61',
    particleSpeed: 1,
    floatAmplitude: 1,
    floatDuration: 6000,
    breathingAmplitude: 0.02,
    speechDriven: false,
  },

  updating: {
    coreColor1: '#00E5F2',
    coreColor2: '#628CFF',
    pulseDuration: 1200,
    pulseSpread: 0.05,
    glowColor: 'rgba(0,229,242,0.16)',
    glowIntensity: 0.18,
    haloVisible: false,
    haloRotationMs: 0,
    ringsVisible: 1,
    ringsOpacity: 0.12,
    ringsColor: '#00E5F2',
    ringScale: 1,
    ringPulseOpacity: { from: 0.05, to: 0.12 },
    ringsRotateMs: 0,
    particlesActive: true,
    particleType: 'orbit',
    particleCount: 3,
    particleColor: '#00E5F2',
    particleSpeed: 0.8,
    floatAmplitude: 1,
    floatDuration: 7000,
    breathingAmplitude: 0.02,
    speechDriven: false,
  },

  sleeping: {
    coreColor1: '#0F2A4A',
    coreColor2: '#00E5F2',
    pulseDuration: 8000,
    pulseSpread: 0.01,
    glowColor: 'rgba(0,229,242,0.06)',
    glowIntensity: 0.08,
    haloVisible: false,
    haloRotationMs: 0,
    ringsVisible: 1,
    ringsOpacity: 0.04,
    ringsColor: '#00E5F2',
    ringScale: 1,
    ringPulseOpacity: { from: 0.02, to: 0.04 },
    ringsRotateMs: 0,
    particlesActive: false,
    particleType: 'none',
    particleCount: 0,
    particleColor: '#00E5F2',
    particleSpeed: 1,
    floatAmplitude: 0.3,
    floatDuration: 8000,
    breathingAmplitude: 0.01,
    speechDriven: false,
  },
};

export const TRANSITION_DURATIONS: Record<string, number> = {
  'idle->listening': 350,
  'listening->thinking': 180,
  'listening->speaking': 320,
  'thinking->speaking': 280,
  'thinking->idle': 320,
  'speaking->idle': 320,
  'speaking->listening': 180,
  'searching->executing': 180,
  'executing->speaking': 220,
  '*-disconnected': 450,
  'disconnected->idle': 450,
  '*-error': 320,
  'error->*': 320,
  '*-success': 320,
  'success->*': 320,
  '*-idle': 320,
  '*-searching': 320,
  '*-executing': 220,
  '*-listening': 350,
  '*-thinking': 280,
  default: 320,
};

export function getTransitionDuration(from: OrbState, to: OrbState): number {
  const key1 = `${from}->${to}`;
  if (TRANSITION_DURATIONS[key1] !== undefined) return TRANSITION_DURATIONS[key1];
  const key2 = `*->${to}`;
  if (TRANSITION_DURATIONS[key2] !== undefined) return TRANSITION_DURATIONS[key2];
  const key3 = `${from}->*`;
  if (TRANSITION_DURATIONS[key3] !== undefined) return TRANSITION_DURATIONS[key3];
  return TRANSITION_DURATIONS.default;
}

export function getStateConfig(state: OrbState): StateConfig {
  return STATE_CONFIGS[state] || STATE_CONFIGS.idle;
}
