import type { StateConfig, OrbState } from './OrbTypes';

export const STATE_CONFIGS: Record<OrbState, StateConfig> = {
  disconnected: {
    coreColor1: '#3A1A1A',
    coreColor2: '#6B1F1F',
    pulseDuration: 2500,
    pulseSpread: 0.3,
    glowColor: 'rgba(69,26,26,0.5)',
    glowIntensity: 0.15,
    haloVisible: false,
    haloRotationSpeed: 0,
    ringsVisible: 1,
    ringsOpacity: 0.08,
    ringsColor: 'rgba(255,69,58,0.12)',
    particlesActive: false,
    particleType: 'none',
    particleCount: 0,
    particleColor: '#FF453A',
    ripplesActive: false,
    rippleCount: 0,
    rippleSpeed: 0,
    floatAmplitude: 0.5,
    floatSpeed: 0.3,
    breathingAmplitude: 0.02,
  },

  connecting: {
    coreColor1: '#1A1A0A',
    coreColor2: '#3A3A0A',
    pulseDuration: 800,
    pulseSpread: 0.6,
    glowColor: 'rgba(255,159,10,0.3)',
    glowIntensity: 0.3,
    haloVisible: true,
    haloRotationSpeed: 1.5,
    ringsVisible: 2,
    ringsOpacity: 0.12,
    ringsColor: 'rgba(255,159,10,0.15)',
    particlesActive: false,
    particleType: 'none',
    particleCount: 0,
    particleColor: '#FF9F0A',
    ripplesActive: true,
    rippleCount: 2,
    rippleSpeed: 0.5,
    floatAmplitude: 1,
    floatSpeed: 0.5,
    breathingAmplitude: 0.04,
  },

  idle: {
    coreColor1: '#0A1A2A',
    coreColor2: '#0F2A4A',
    pulseDuration: 2500,
    pulseSpread: 0.4,
    glowColor: 'rgba(0,242,255,0.15)',
    glowIntensity: 0.2,
    haloVisible: false,
    haloRotationSpeed: 0,
    ringsVisible: 2,
    ringsOpacity: 0.1,
    ringsColor: 'rgba(0,242,255,0.08)',
    particlesActive: false,
    particleType: 'none',
    particleCount: 0,
    particleColor: '#00F2FF',
    ripplesActive: false,
    rippleCount: 0,
    rippleSpeed: 0,
    floatAmplitude: 2,
    floatSpeed: 1,
    breathingAmplitude: 0.03,
  },

  listening: {
    coreColor1: '#0A2A3A',
    coreColor2: '#005F7F',
    pulseDuration: 1000,
    pulseSpread: 0.6,
    glowColor: 'rgba(0,242,255,0.35)',
    glowIntensity: 0.4,
    haloVisible: false,
    haloRotationSpeed: 0,
    ringsVisible: 3,
    ringsOpacity: 0.18,
    ringsColor: 'rgba(0,242,255,0.15)',
    particlesActive: false,
    particleType: 'none',
    particleCount: 0,
    particleColor: '#00F2FF',
    ripplesActive: true,
    rippleCount: 3,
    rippleSpeed: 1,
    floatAmplitude: 1.5,
    floatSpeed: 0.8,
    breathingAmplitude: 0.05,
  },

  thinking: {
    coreColor1: '#1A0A3A',
    coreColor2: '#5A3FBF',
    pulseDuration: 600,
    pulseSpread: 0.8,
    glowColor: 'rgba(90,63,191,0.4)',
    glowIntensity: 0.45,
    haloVisible: true,
    haloRotationSpeed: 0.8,
    ringsVisible: 3,
    ringsOpacity: 0.2,
    ringsColor: 'rgba(90,63,191,0.18)',
    particlesActive: true,
    particleType: 'orbit',
    particleCount: 4,
    particleColor: '#BC8CFF',
    ripplesActive: false,
    rippleCount: 0,
    rippleSpeed: 0,
    floatAmplitude: 1,
    floatSpeed: 1.2,
    breathingAmplitude: 0.06,
  },

  searching: {
    coreColor1: '#0A2A2A',
    coreColor2: '#007F6F',
    pulseDuration: 1200,
    pulseSpread: 0.5,
    glowColor: 'rgba(0,127,111,0.3)',
    glowIntensity: 0.3,
    haloVisible: true,
    haloRotationSpeed: 0.5,
    ringsVisible: 2,
    ringsOpacity: 0.14,
    ringsColor: 'rgba(0,127,111,0.12)',
    particlesActive: true,
    particleType: 'converge',
    particleCount: 5,
    particleColor: '#00F2FF',
    ripplesActive: true,
    rippleCount: 2,
    rippleSpeed: 0.4,
    floatAmplitude: 1.5,
    floatSpeed: 0.6,
    breathingAmplitude: 0.04,
  },

  memory_retrieval: {
    coreColor1: '#1A0A2A',
    coreColor2: '#4A2A7F',
    pulseDuration: 900,
    pulseSpread: 0.6,
    glowColor: 'rgba(188,140,255,0.35)',
    glowIntensity: 0.4,
    haloVisible: true,
    haloRotationSpeed: 0.6,
    ringsVisible: 3,
    ringsOpacity: 0.18,
    ringsColor: 'rgba(188,140,255,0.15)',
    particlesActive: true,
    particleType: 'fragments',
    particleCount: 6,
    particleColor: '#BC8CFF',
    ripplesActive: false,
    rippleCount: 0,
    rippleSpeed: 0,
    floatAmplitude: 0.8,
    floatSpeed: 0.7,
    breathingAmplitude: 0.05,
  },

  executing: {
    coreColor1: '#0A1A3A',
    coreColor2: '#004FBF',
    pulseDuration: 800,
    pulseSpread: 0.8,
    glowColor: 'rgba(0,79,191,0.5)',
    glowIntensity: 0.5,
    haloVisible: true,
    haloRotationSpeed: 1.2,
    ringsVisible: 3,
    ringsOpacity: 0.25,
    ringsColor: 'rgba(0,242,255,0.2)',
    particlesActive: true,
    particleType: 'hexagonal',
    particleCount: 6,
    particleColor: '#00F2FF',
    ripplesActive: false,
    rippleCount: 0,
    rippleSpeed: 0,
    floatAmplitude: 1.2,
    floatSpeed: 1.5,
    breathingAmplitude: 0.07,
  },

  speaking: {
    coreColor1: '#003F5F',
    coreColor2: '#00F2FF',
    pulseDuration: 400,
    pulseSpread: 1.0,
    glowColor: 'rgba(0,242,255,0.5)',
    glowIntensity: 0.6,
    haloVisible: false,
    haloRotationSpeed: 0,
    ringsVisible: 3,
    ringsOpacity: 0.3,
    ringsColor: 'rgba(0,242,255,0.25)',
    particlesActive: true,
    particleType: 'orbit',
    particleCount: 6,
    particleColor: '#00F2FF',
    ripplesActive: true,
    rippleCount: 3,
    rippleSpeed: 1.5,
    floatAmplitude: 2,
    floatSpeed: 2,
    breathingAmplitude: 0.08,
  },

  success: {
    coreColor1: '#0A2A1A',
    coreColor2: '#3FB950',
    pulseDuration: 800,
    pulseSpread: 0.9,
    glowColor: 'rgba(63,185,80,0.5)',
    glowIntensity: 0.5,
    haloVisible: false,
    haloRotationSpeed: 0,
    ringsVisible: 2,
    ringsOpacity: 0.2,
    ringsColor: 'rgba(63,185,80,0.2)',
    particlesActive: true,
    particleType: 'scatter',
    particleCount: 4,
    particleColor: '#3FB950',
    ripplesActive: true,
    rippleCount: 2,
    rippleSpeed: 0.8,
    floatAmplitude: 1,
    floatSpeed: 0.5,
    breathingAmplitude: 0.05,
  },

  warning: {
    coreColor1: '#2A1A0A',
    coreColor2: '#7F4F00',
    pulseDuration: 600,
    pulseSpread: 0.7,
    glowColor: 'rgba(255,159,10,0.4)',
    glowIntensity: 0.4,
    haloVisible: true,
    haloRotationSpeed: 0.4,
    ringsVisible: 2,
    ringsOpacity: 0.15,
    ringsColor: 'rgba(255,159,10,0.15)',
    particlesActive: false,
    particleType: 'none',
    particleCount: 0,
    particleColor: '#FF9F0A',
    ripplesActive: false,
    rippleCount: 0,
    rippleSpeed: 0,
    floatAmplitude: 1.5,
    floatSpeed: 0.4,
    breathingAmplitude: 0.04,
  },

  error: {
    coreColor1: '#2A0A0A',
    coreColor2: '#7F1F1F',
    pulseDuration: 500,
    pulseSpread: 0.6,
    glowColor: 'rgba(255,69,58,0.5)',
    glowIntensity: 0.4,
    haloVisible: false,
    haloRotationSpeed: 0,
    ringsVisible: 1,
    ringsOpacity: 0.12,
    ringsColor: 'rgba(255,69,58,0.15)',
    particlesActive: true,
    particleType: 'scatter',
    particleCount: 8,
    particleColor: '#FF453A',
    ripplesActive: false,
    rippleCount: 0,
    rippleSpeed: 0,
    floatAmplitude: 2,
    floatSpeed: 0.3,
    breathingAmplitude: 0.03,
  },

  updating: {
    coreColor1: '#0A1A2A',
    coreColor2: '#0F2A4A',
    pulseDuration: 1500,
    pulseSpread: 0.5,
    glowColor: 'rgba(0,242,255,0.25)',
    glowIntensity: 0.25,
    haloVisible: true,
    haloRotationSpeed: 0.3,
    ringsVisible: 2,
    ringsOpacity: 0.12,
    ringsColor: 'rgba(0,242,255,0.1)',
    particlesActive: true,
    particleType: 'orbit',
    particleCount: 3,
    particleColor: '#00F2FF',
    ripplesActive: false,
    rippleCount: 0,
    rippleSpeed: 0,
    floatAmplitude: 1,
    floatSpeed: 0.5,
    breathingAmplitude: 0.04,
  },

  sleeping: {
    coreColor1: '#050A0F',
    coreColor2: '#081524',
    pulseDuration: 4000,
    pulseSpread: 0.2,
    glowColor: 'rgba(0,242,255,0.06)',
    glowIntensity: 0.08,
    haloVisible: false,
    haloRotationSpeed: 0,
    ringsVisible: 1,
    ringsOpacity: 0.04,
    ringsColor: 'rgba(0,242,255,0.04)',
    particlesActive: false,
    particleType: 'none',
    particleCount: 0,
    particleColor: '#00F2FF',
    ripplesActive: false,
    rippleCount: 0,
    rippleSpeed: 0,
    floatAmplitude: 0.3,
    floatSpeed: 0.2,
    breathingAmplitude: 0.01,
  },
};

export const TRANSITION_DURATIONS: Record<string, number> = {
  'idle->listening': 200,
  'listening->thinking': 150,
  'thinking->speaking': 200,
  'thinking->idle': 300,
  'speaking->idle': 400,
  'speaking->listening': 200,
  '*-disconnected': 400,
  'disconnected->idle': 600,
  '*-error': 250,
  'error->*': 400,
  '*-success': 300,
  'success->*': 400,
  '*-idle': 300,
  default: 300,
};

export function getTransitionDuration(from: OrbState, to: OrbState): number {
  const key1 = `${from}->${to}`;
  if (TRANSITION_DURATIONS[key1] !== undefined) return TRANSITION_DURATIONS[key1];
  const key2 = `*->${to}`;
  if (TRANSITION_DURATIONS[key2] !== undefined) return TRANSITION_DURATIONS[key2];
  const key3 = `${from}->*`;
  if (TRANSITION_DURATIONS[key3] !== undefined) return TRANSITION_DURATIONS[key3];
  return TRANSITION_DURATIONS.default;
}

export function getStateConfig(state: OrbState): StateConfig {
  return STATE_CONFIGS[state] || STATE_CONFIGS.idle;
}
