"""Tool definitions exposed to the LLM."""

TOOLS = [
    # ── Audio ──────────────────────────────────────────────────────────────────
    {"type": "function", "function": {"name": "set_volume", "description": "Set system volume (0–100).", "parameters": {"type": "object", "properties": {"level": {"type": "integer", "minimum": 0, "maximum": 100}}, "required": ["level"]}}},
    {"type": "function", "function": {"name": "get_volume", "description": "Get current system volume.", "parameters": {"type": "object", "properties": {}, "required": []}}},
    {"type": "function", "function": {"name": "mute_audio", "description": "Mute or unmute system audio.", "parameters": {"type": "object", "properties": {"muted": {"type": "boolean", "description": "True to mute, False to unmute."}}, "required": []}}},
    # ── Media ──────────────────────────────────────────────────────────────────
    {"type": "function", "function": {"name": "play_pause", "description": "Toggle play/pause on current media.", "parameters": {"type": "object", "properties": {}, "required": []}}},
    {"type": "function", "function": {"name": "next_track", "description": "Skip to next track.", "parameters": {"type": "object", "properties": {}, "required": []}}},
    {"type": "function", "function": {"name": "prev_track", "description": "Go to previous track.", "parameters": {"type": "object", "properties": {}, "required": []}}},
    # ── Apps ───────────────────────────────────────────────────────────────────
    {"type": "function", "function": {"name": "launch_app", "description": "Launch an application by name.", "parameters": {"type": "object", "properties": {"app_name": {"type": "string"}}, "required": ["app_name"]}}},
    {"type": "function", "function": {"name": "list_running_processes", "description": "List currently running processes.", "parameters": {"type": "object", "properties": {"filter_pattern": {"type": "string", "description": "Optional name filter."}}, "required": []}}},
    # ── Files ──────────────────────────────────────────────────────────────────
    {"type": "function", "function": {"name": "open_path", "description": "Open a file, folder, or shortcut (downloads, desktop, documents, etc).", "parameters": {"type": "object", "properties": {"path": {"type": "string"}}, "required": ["path"]}}},
    {"type": "function", "function": {"name": "create_folder", "description": "Create a new folder at the given path.", "parameters": {"type": "object", "properties": {"folder_path": {"type": "string"}}, "required": ["folder_path"]}}},
    {"type": "function", "function": {"name": "list_directory", "description": "List files and folders in a directory.", "parameters": {"type": "object", "properties": {"dir_path": {"type": "string"}}, "required": []}}},
    # ── Web ────────────────────────────────────────────────────────────────────
    {"type": "function", "function": {"name": "web_search", "description": "Search the web for current info, news, facts.", "parameters": {"type": "object", "properties": {"query": {"type": "string"}}, "required": ["query"]}}},
    {"type": "function", "function": {"name": "open_website", "description": "Open a URL or website in the default browser. If the user says 'open X' or 'go to Y', construct the full URL. E.g. 'open youtube' → 'https://youtube.com', 'open youtube recipes' → 'https://www.youtube.com/results?search_query=recipes', 'open google' → 'https://google.com'. Always include the protocol prefix.", "parameters": {"type": "object", "properties": {"url": {"type": "string"}}, "required": ["url"]}}},
    {"type": "function", "function": {"name": "open_z_agent", "description": "Open chat.z.ai in Agent mode and submit a prompt for GLM-5.1 to build an app, website, or project. Call this when user asks to MAKE, CREATE, BUILD, or GENERATE something. SILENTLY elaborate their vague idea into a concise directive (what, features, tech stack) — DO NOT show it to the user. Just call the tool.", "parameters": {"type": "object", "properties": {"elaborated_prompt": {"type": "string", "description": "Expanded app/project directive for GLM-5.1 Agent"}}, "required": ["elaborated_prompt"]}}},
    {"type": "function", "function": {"name": "scrape_website", "description": "Open a URL in a headless browser, wait for it to load, and return the visible text content. Use this when you need to read/extract information from a live website — get article text, check a page, look up docs, compare pricing, etc. Returns title + body text.", "parameters": {"type": "object", "properties": {"url": {"type": "string", "description": "Full URL to scrape (including protocol)"}}, "required": ["url"]}}},
    # ── System ─────────────────────────────────────────────────────────────────
    {"type": "function", "function": {"name": "get_system_stats", "description": "Get CPU, RAM, and disk usage.", "parameters": {"type": "object", "properties": {}, "required": []}}},
    {"type": "function", "function": {"name": "shutdown", "description": "Shut down the PC after a delay.", "parameters": {"type": "object", "properties": {"delay_seconds": {"type": "integer", "default": 20}}, "required": []}}},
    {"type": "function", "function": {"name": "restart", "description": "Restart the PC.", "parameters": {"type": "object", "properties": {"delay_seconds": {"type": "integer", "default": 30}}, "required": []}}},
    {"type": "function", "function": {"name": "sleep_pc", "description": "Put the PC to sleep.", "parameters": {"type": "object", "properties": {}, "required": []}}},
    {"type": "function", "function": {"name": "lock_pc", "description": "Lock the Windows session.", "parameters": {"type": "object", "properties": {}, "required": []}}},
    {"type": "function", "function": {"name": "lock_screen", "description": "Alias for locking the Windows session.", "parameters": {"type": "object", "properties": {}, "required": []}}},
    {"type": "function", "function": {"name": "cancel_shutdown", "description": "Cancel a pending shutdown or restart.", "parameters": {"type": "object", "properties": {}, "required": []}}},
    # ── Clipboard ──────────────────────────────────────────────────────────────
    {"type": "function", "function": {"name": "clipboard_copy", "description": "Copy text to the clipboard.", "parameters": {"type": "object", "properties": {"text": {"type": "string"}}, "required": ["text"]}}},
    {"type": "function", "function": {"name": "clipboard_paste", "description": "Read current clipboard contents.", "parameters": {"type": "object", "properties": {}, "required": []}}},
    # ── Vault (Obsidian notes) ─────────────────────────────────────────────────
    {"type": "function", "function": {"name": "vault", "description": "Interact with the user's Obsidian vault — search, read, create, append, delete notes.\n\nACTIONS:\n- \"search\" — semantic search across all vault notes. Use when you need relevant context from the user's notes.\n- \"read\" — read a note's full content by title (filename without .md).\n- \"list\" — list all AURA notes in the vault.\n- \"create\" — create a new note (AURA writes to her own AURA/ folder). Include wikilinks [[LikeThis]] to connect it to related notes.\n- \"append\" — append content to an existing AURA note.\n- \"delete\" — delete an AURA note.\n- \"reindex\" — re-scan the vault for new/changed notes.\n\nUse this tool proactively when the user asks about their notes, studies, projects, or anything that might be documented in their vault.", "parameters": {"type": "object", "properties": {"action": {"type": "string", "enum": ["search", "read", "list", "create", "append", "delete", "reindex"]}, "title": {"type": "string", "description": "Note title (filename stem, no extension)"}, "content": {"type": "string", "description": "Content for create/append actions"}, "query": {"type": "string", "description": "Search query for semantic search"}, "folder": {"type": "string", "description": "Subfolder under AURA/ (used with list/create)"}}, "required": ["action"]}}},
    # ── Study (vault-based) ────────────────────────────────────────────────────
    {"type": "function", "function": {"name": "study", "description": "Study assistance using your vault notes — quiz, summarize, or draft assignments.\n\nHOW TO USE:\n1. Call this tool with a topic and action.\n2. It searches your vault, reads the top relevant notes, and returns their content.\n3. Use the returned notes to generate the output the user asked for.\n\nACTIONS:\n- \"quiz\" — generate practice questions from the notes\n- \"summarize\" — summarize the key concepts from the notes\n- \"draft\" — draft an assignment answer using the notes as reference", "parameters": {"type": "object", "properties": {"topic": {"type": "string", "description": "The subject or topic to study (e.g. 'paging OS', 'normalization DBMS')"}, "action": {"type": "string", "enum": ["quiz", "summarize", "draft"]}}, "required": ["topic", "action"]}}},
    # ── Input ──────────────────────────────────────────────────────────────────
    {"type": "function", "function": {"name": "type_text", "description": "Type text using the keyboard.", "parameters": {"type": "object", "properties": {"text": {"type": "string"}}, "required": ["text"]}}},
    {"type": "function", "function": {"name": "press_key", "description": "Press a keyboard key (e.g. enter, tab, escape).", "parameters": {"type": "object", "properties": {"key": {"type": "string"}}, "required": ["key"]}}},
    {"type": "function", "function": {"name": "execute_hotkey", "description": "Execute a keyboard shortcut like ctrl+c.", "parameters": {"type": "object", "properties": {"keys": {"type": "string", "description": "Keys joined by +, e.g. 'ctrl+c'"}}, "required": ["keys"]}}},
    # ── Communication ──────────────────────────────────────────────────────────
    {"type": "function", "function": {"name": "send_whatsapp", "description": "Send a WhatsApp message to a saved contact.", "parameters": {"type": "object", "properties": {"contact": {"type": "string", "description": "Contact name (e.g. mom, dad, etc.) — check your contacts list in the system prompt for valid names."}, "message": {"type": "string"}}, "required": ["contact", "message"]}}},
    # ── Memory ─────────────────────────────────────────────────────────────────
    # Hermes-style behavioral guidance: tells the LLM WHEN/WHY to invoke the tool
    {"type": "function", "function": {"name": "memory", "description": "Remember facts about the user or yourself so you can recall them across sessions.\n\nWHEN to SAVE:\n- User states a preference, opinion, or habit (\"I like X\", \"I usually do Y\")\n- User gives personal details (name, location, job, hobbies, family, pets)\n- User corrects something you said or did — save the correction\n- User says \"remember this\", \"keep that in mind\", \"don't forget\"\n- User sets a goal, deadline, or recurring task they care about\n- User reveals an environment fact (\"my path is Z\", \"I use editor W\")\n- You discover a pattern or convention the user follows\n\nWHEN to SKIP:\n- Task progress or step-by-step status (session-specific)\n- Temporary state like \"currently doing X\" that won't persist\n- One-off file paths, URLs, or ephemeral data\n- Trivial acknowledgments\n\nPRIORITY ORDER:\n1. User preferences, corrections, and personal identity facts\n2. Environment facts (paths, tools, setup)\n3. Procedural knowledge (how to do something for this user)\n4. Operational notes about yourself\n\nCATEGORY:\n- \"user\" — facts about the user (preferences, identity, habits, environment)\n- \"self\" — your own operational notes, rules of thumb, things you learned about being helpful to this user\n\nACTIONS:\n- \"add\" — save a new memory entry\n- \"replace\" — update an existing entry (provide identifier as unique substring match)\n- \"remove\" — delete an entry by unique substring\n- \"search\" — search past conversations (ChromaDB) for relevant snippets based on a query\n- \"list\" — show all current curated memories for a category", "parameters": {"type": "object", "properties": {"action": {"type": "string", "enum": ["add", "replace", "remove", "search", "list"]}, "category": {"type": "string", "enum": ["user", "self"], "description": "Where to store the memory: 'user' for facts about the user, 'self' for your own operational notes."}, "text": {"type": "string", "description": "The memory content or search query (required for add/replace/search)."}, "identifier": {"type": "string", "description": "A unique substring to locate the entry for replacement or removal (required for replace/remove)."}}, "required": ["action"]}}},
]

TOOL_NAMES = {t["function"]["name"] for t in TOOLS}